# Generated by Django 3.2.6 on 2024-06-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='access_code',
            field=models.CharField(default='BReefE', max_length=6, unique=True),
        ),
    ]
