# Generated by Django 3.2.6 on 2024-06-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20240612_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='access_code',
            field=models.CharField(default='XeaOkK', max_length=6, unique=True),
        ),
    ]
