# Generated by Django 3.2.6 on 2024-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_alter_referral_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='access_code',
            field=models.CharField(default='lEH2qD', max_length=6, unique=True),
        ),
    ]
