# Generated by Django 3.2.6 on 2024-07-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultation_clinician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='clinician',
        ),
    ]
